services:

  monitor-sensors:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitor_sensors
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor_sensors